# Site settings
title: Survey on Media Consumption &middot; Results
author: Fabian Schultz
email: desk@fabianschultz.com
description: > # this means to ignore newlines until "baseurl:"
  Everybody consumes, uses and sees media in a different way. 
  This survey rises ten related questions and will be a foundation
  for a student project at the University of Applied Sciences in
  Potsdam, Germany.
baseurl: "/media-consumption" # the subpath of your site, e.g. /blog/
url: "https://fabianschultz.com/media-consumption" # the base hostname & protocol for your site
twitter_username: fschultz_
github_username:  fabe
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

# Build settings
markdown: kramdown
